# Generated by Django 3.2.6 on 2021-09-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training',
            new_name='Formation',
        ),
    ]
